### ISSUE TITLE
Is it possible to rewire deps with the same unscoped module name as module under test?

### ISSUE THREAD

**Issue by parkerjm** [stephanos/rewire#17]
Given two modules:
- App.Connector.Hubspot (used by app to interact with external resource)
- App.Client.Hubspot (used by connector to make external calls)

It is not possible to (easily?) inject a mock for the client in the connector tests, since:
- elixir does not support the syntax: `rewire App.Connector.Hubspot, App.Client.Hubspot: HubspotMock`
- aliasing `App.Client.Hubspot` is ambiguous since the connector has the same module name

It seems plausible it could work with some alias tweaking, but this could be more easily solved by accepting a list of tuples instead of a keyword list, perhaps? Hopefully I can look more into this later.

**Comment by parkerjm** [comment]
I got it to work now, just had to namespace the mock like `App.Client.HubspotMock` then alias it. I guess the namespace of the mock has to match the namespace of the dependency. Maybe this just needs some documentation? I can make a PR if you agree.

**Comment by parkerjm** [comment]
Please disregard everything above. I just had some misunderstandings. I see now.

**Comment by stephanos** [comment]
:) I'd still be interested to hear whether you think I can make something clearer in the docs/README!

**Comment by parkerjm** [comment]
my misconception, which makes little sense in retrospect, was that I thought this lib removed the need to define behaviors for every module I wanted to mock when using Mox. now I understand that I still need behaviors and mock module definitions, and that this lib removes the need to have extra config everywhere to inject modules. after discussing the issue, I realized that having these behaviors is a good thing anyways, and that I could simply nest the behavior definition inside the modules to prevent having a ton of behavior files laying around.

anyways, the ability to remove all of the dep injection config and lookup function calls is still a huge win and I am a happy customer. :) thanks for making this.

**Comment by stephanos** [comment]
awesome, glad to hear that! Yeah, I saw it from the unix philosophy of "make each program do one thing well" :)

**Comment by carlows** [comment]
@parkerjm could you expand on what you saw back then? I don't understand how it is supposed to work :)

**Comment by carlows** [comment]
Nvm my problem wasn't related, I had to include this in my test helper:

> Application.ensure_all_started(:rewire)

Else I get:

> (UndefinedFunctionError) function :cover.compile_beams/1 is undefined or private.
